items:
  BLANK:
    ==: org.bukkit.inventory.ItemStack
    v: 2584
    type: GRAY_STAINED_GLASS_PANE
    meta:
      ==: ItemMeta
      meta-type: UNSPECIFIC
      display-name: ' '
  FORWARD:
    ==: org.bukkit.inventory.ItemStack
    v: 2584
    type: GREEN_STAINED_GLASS_PANE
    meta:
      ==: ItemMeta
      meta-type: UNSPECIFIC
      display-name: §aForward
  BACK:
    ==: org.bukkit.inventory.ItemStack
    v: 2584
    type: RED_STAINED_GLASS_PANE
    meta:
      ==: ItemMeta
      meta-type: UNSPECIFIC
      display-name: §cBack
